#! /bin/csh -f

if ($#argv != 1) then
    echo "Usage $0 commit-message"
    exit 1
endif

rm -rf build
rm .DS_Store
rm */.DS_Store
rm -rf *.xcodeproj/ericasadun.*
git add -A
git commit -m "$1"
git push
